In [1]:
import aocd
import numpy as np

In [4]:
DAY=2
YEAR=2022

raw_data=aocd.get_data(day=DAY, year=YEAR)
rounds_raw=aocd.transforms.lines(raw_data)

In [34]:
rounds=np.array([list(R) for R in rounds_raw])[:,[0,2]]

In [10]:
rounds

array([['C', 'Y'],
       ['A', 'Z'],
       ['B', 'X'],
       ...,
       ['A', 'Y'],
       ['C', 'Y'],
       ['B', 'X']], dtype='<U1')

In [13]:
recode={
    "A":1,
    "B":2,
    "C":3,
    "X":1,
    "Y":2,
    "Z":3,
}

for k in recode:
    rounds[rounds==k]=recode[k]

rounds=rounds.astype("int")

In [29]:
rounds[:10]

array([[3, 2],
       [1, 3],
       [2, 1],
       [3, 2],
       [2, 2],
       [3, 1],
       [3, 2],
       [2, 1],
       [2, 1],
       [1, 3]])

In [30]:
points=(rounds[:,1]+ 3*(rounds[:,0]==rounds[:,1])+6*(np.mod(rounds[:,0]+1,3)==np.mod(rounds[:,1],3))).reshape(-1,1)
points[:10]

array([[2],
       [3],
       [1],
       [2],
       [5],
       [7],
       [2],
       [1],
       [1],
       [3]])

In [32]:
np.sum(points)

8392

In [66]:
recode={
    "A":0,
    "B":1,
    "C":2,
    "X":-1,
    "Y":0,
    "Z":1,
}

rounds=np.array([list(R) for R in rounds_raw])[:,[0,2]]

for k in recode:
    rounds=np.where(rounds==k, recode[k], rounds)

rounds=rounds.astype(np.int16)

In [67]:
rounds[:,1]=np.mod((np.sum(rounds,1)),3)

In [68]:
points=(rounds[:,1]+1+ 3*(rounds[:,0]==rounds[:,1])+6*(np.mod(rounds[:,0]+1,3)==np.mod(rounds[:,1],3))).reshape(-1,1)
points[:10]

array([[6],
       [8],
       [1],
       [6],
       [5],
       [2],
       [6],
       [1],
       [1],
       [8]])

In [69]:
np.sum(points)


10116