In [1]:
import aocd
import numpy as np


In [4]:
DAY=4
YEAR=2022

raw_data=aocd.get_data(day=DAY, year=YEAR)
data=aocd.transforms.lines(raw_data)

In [17]:
data_num=np.array([aocd.transforms.numbers(row.replace("-", " ")) for row in data])
data_num[:10]

array([[48, 50, 48, 49],
       [ 5, 89,  5,  5],
       [17, 57, 55, 96],
       [24, 67, 23, 25],
       [89, 99, 11, 89],
       [34, 71, 35, 71],
       [13, 17, 16, 95],
       [13, 93,  5, 12],
       [11, 91,  1, 11],
       [ 4, 81,  2, 11]])

In [21]:
contains=(data_num[:,0]<=data_num[:,2]) & (data_num[:,1]>=data_num[:,3]) | (data_num[:,2]<=data_num[:,0]) & (data_num[:,3]>=data_num[:,1])
contains[:10].reshape(-1,1)

array([[ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False]])

In [22]:
np.sum(contains)

530

In [25]:
intersect=((data_num[:,1]>=data_num[:,2]) & (data_num[:,0]<=data_num[:,3])) | ((data_num[:,3]>=data_num[:,0]) & (data_num[:,2]<=data_num[:,1])) 
intersect[:10].reshape(-1,1)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True]])

In [26]:
np.sum(intersect)

903